
package soap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServerService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/Hello?wsdl")
public class HelloServerService
    extends Service
{

    private final static URL HELLOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVERSERVICE_EXCEPTION;
    private final static QName HELLOSERVERSERVICE_QNAME = new QName("http://soap/", "HelloServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVERSERVICE_WSDL_LOCATION = url;
        HELLOSERVERSERVICE_EXCEPTION = e;
    }

    public HelloServerService() {
        super(__getWsdlLocation(), HELLOSERVERSERVICE_QNAME);
    }

    public HelloServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVERSERVICE_QNAME, features);
    }

    public HelloServerService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVERSERVICE_QNAME);
    }

    public HelloServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVERSERVICE_QNAME, features);
    }

    public HelloServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloServer
     */
    @WebEndpoint(name = "HelloServerPort")
    public HelloServer getHelloServerPort() {
        return super.getPort(new QName("http://soap/", "HelloServerPort"), HelloServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServer
     */
    @WebEndpoint(name = "HelloServerPort")
    public HelloServer getHelloServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "HelloServerPort"), HelloServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVERSERVICE_EXCEPTION!= null) {
            throw HELLOSERVERSERVICE_EXCEPTION;
        }
        return HELLOSERVERSERVICE_WSDL_LOCATION;
    }

}
